name: pywrf
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - attr=2.5.1=h166bdaf_1
  - binutils=2.39=hdd6e379_1
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - blosc=1.21.6=hef167b5_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-compiler=1.3.0=h7f98852_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.16.0=ha61ee94_1012
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cftime=1.6.4=py311h9f3472d_1
  - contourpy=1.3.2=py311hd18a35c_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - curl=8.1.2=h409715c_0
  - cxx-compiler=1.3.0=h4bd325d_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h9033bb2_6
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - einops=0.8.1=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.0=py311h2dc5d0c_0
  - fortran-compiler=1.3.0=h1990efc_0
  - freetype=2.13.3=ha770c72_1
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gcc=9.5.0=h1fea6ba_13
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gcc_linux-64=9.5.0=h4258300_13
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - gfortran=9.5.0=hdd025ce_13
  - gfortran_impl_linux-64=9.5.0=hf1096a2_19
  - gfortran_linux-64=9.5.0=hdb51d14_13
  - glib=2.84.1=h6287aef_1
  - glib-tools=2.84.1=h4833e2c_1
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_1
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.41=h17648ed_0
  - gxx=9.5.0=h1fea6ba_13
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - gxx_linux-64=9.5.0=h43f449f_13
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=70.1=h27087fc_0
  - jack=1.9.22=h11f4161_0
  - jasper=1.900.1=h07fcdf6_1006
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.1.2=h409715c_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.7.0=h5888daf_0
  - libfabric=2.0.0=ha770c72_0
  - libfabric1=2.0.0=ha594dbc_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt=1.11.1=ha770c72_0
  - libgcrypt-devel=1.11.1=hb9d3cd8_0
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgcrypt-tools=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libglib=2.84.1=h3618099_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm15=15.0.7=hadd5161_1
  - libltdl=2.4.3a=h5888daf_0
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libnetcdf=4.9.1=nompi_h34a3ff0_101
  - libnghttp2=1.58.0=h47da74e_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=5.28.3=h6128344_1
  - libsanitizer=9.5.0=h2f262e1_19
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.49.2=hee588c1_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=253=h8c4010b_1
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.5.4=h5888daf_0
  - libtorch=2.6.0=cpu_generic_haed06de_0
  - libudev1=253=h0b41bf4_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libxslt=1.1.37=h873f0b0_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib=3.9.1=py311h38be061_1
  - matplotlib-base=3.9.1=py311h74b4f7c_2
  - meson=1.8.1=pyhe01879c_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpi=1.0.1=mpich
  - mpi4py=4.0.3=py311had46f3b_0
  - mpich=4.2.3=h670b19f_100
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.5=h2d0b736_3
  - netcdf-fortran=4.6.0=nompi_heb5813c_103
  - netcdf4=1.6.3=nompi_py311ha396515_100
  - networkx=3.5=pyhe01879c_0
  - ninja=1.12.1=hff21bea_1
  - nomkl=1.0=h5ca1d4c_0
  - nspr=4.36=h5888daf_0
  - nss=3.111=h159eef7_0
  - numpy=1.26.4=py311h64a7726_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openldap=2.6.5=h389dcaa_0
  - openssl=3.1.8=h7b32b05_0
  - optree=0.17.0=py311hdf67eae_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py311h7db5c69_3
  - pcre2=10.45=hc749103_0
  - pillow=9.4.0=py311h50def17_1
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - ply=3.11=pyhd8ed1ab_3
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.9=py311hf0fb5b6_5
  - pyqt5-sip=12.12.2=py311hb755f60_5
  - python=3.11.6=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=h5d23da1_6
  - rdma-core=54.0=h5888daf_0
  - readline=8.2=h8c095d6_2
  - setuptools=59.8.0=py311h38be061_1
  - sip=6.7.12=py311hb755f60_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.1=h8bd8927_1
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5=py311h9ecbd09_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucc=1.3.0=h0f835a6_3
  - ucx=1.17.0=h05e919c_3
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - wayland=1.23.1=h3e06ad9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2025.4.0=pyhd8ed1ab_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-cursor=0.1.4=hd590300_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-libxxf86vm=1.1.5=h0b41bf4_0
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - anyio==4.11.0
      - asttokens==3.0.0
      - attrs==25.4.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - executing==2.2.1
      - fairscale==0.4.13
      - fastjsonschema==2.21.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - idna==3.11
      - ipython==8.12.3
      - jedi==0.19.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pytorch-msssim==1.0.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - timm==1.0.21
      - tinycss2==1.4.0
      - torch==2.9.0
      - torchinfo==1.8.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.5.0
      - typer-slim==0.20.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - yarg==0.1.9
prefix: /home/ouc/zhuxianrui/environment/miniconda3/envs/pywrf
