name: pycm2
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.1=h166bdaf_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h92a005d_16
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h0c2b49e_1
  - aws-c-http=0.10.2=hee85082_3
  - aws-c-io=0.21.0=h1d8da38_1
  - aws-c-mqtt=0.13.1=h46c1de9_4
  - aws-c-s3=0.8.3=h9cdc349_1
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.32.10=h186f887_3
  - aws-sdk-cpp=1.11.510=h379b65b_14
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - bokeh=3.7.3=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py311hfdbb021_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cdsapi=0.7.7=pyhd8ed1ab_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - cmake=4.0.3=h74e3db0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py311hd18a35c_0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cuda-crt-tools=12.9.86=ha770c72_1
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hbd13f7d_0
  - cuda-cupti=12.9.79=h9ab20c4_0
  - cuda-nvcc-tools=12.9.86=he02047a_1
  - cuda-nvdisasm=12.9.88=hbd13f7d_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-nvvm-tools=12.9.86=he02047a_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.1.4=h7646684_0
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - cytoolz=1.0.1=py311h9ecbd09_0
  - dask=2025.7.0=pyhe01879c_0
  - dask-core=2025.7.0=pyhe01879c_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - distributed=2025.7.0=pyhe01879c_0
  - double-conversion=3.3.1=h5888daf_0
  - ecmwf-datastores-client=0.4.0=pyhd8ed1ab_0
  - einops=0.8.1=pyhd8ed1ab_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.5=py311h2dc5d0c_0
  - freetype=2.13.3=ha770c72_1
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - gdb=16.3=py311h3451168_2
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h0f6cedb_0
  - graphite2=1.3.14=h5888daf_0
  - grpcio=1.71.0=py311h8825b61_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h3beb420_0
  - hf-xet=1.1.8=py39h598437d_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - huggingface_hub=0.34.4=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - kaldi=5.5.1112=cuda126h9941629_9
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py311hd18a35c_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libarrow=20.0.0=h019e7cd_8_cuda
  - libarrow-acero=20.0.0=hb826db4_8_cuda
  - libarrow-dataset=20.0.0=hb826db4_8_cuda
  - libarrow-substrait=20.0.0=h69308b4_8_cuda
  - libavif16=1.3.0=h35444bf_1
  - libblas=3.9.0=32_hfdb39a5_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=32_h372d94f_mkl
  - libclang-cpp20.1=20.1.7=default_h1df26ce_0
  - libclang13=20.1.7=default_he06ed0a_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcudnn=9.10.1.4=h4840ae0_0
  - libcudnn-dev=9.10.1.4=hcd2ec93_0
  - libcudss=0.6.0.5=hcd2ec93_0
  - libcufft=11.4.1.4=h5888daf_0
  - libcufile=1.14.1.1=ha8da6e3_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.7.5.82=h9ab20c4_0
  - libcusparse=12.5.10.65=h5888daf_0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.0=h5888daf_0
  - libfabric=2.2.0=ha770c72_0
  - libfabric1=2.2.0=hf45584d_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.71.0=h8e591d7_1
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_hc41d3b0_mkl
  - liblapacke=3.9.0=32_hbc6e62b_mkl
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=h19665d7_1
  - libmagma_sparse=2.9.0=h4951f4c_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=h5888daf_1
  - libnvjpeg=12.4.0.76=h5888daf_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_0
  - libparquet=20.0.0=h3f30f2e_8_cuda
  - libpciaccess=0.18=hb9d3cd8_0
  - libpmix=5.0.8=h658e747_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=5.29.3=h501fc15_1
  - libre2-11=2025.06.26=hba17884_0
  - libsqlite=3.50.2=h6cd9bfd_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.7=h4e0b6ca_0
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hf01ce69_5
  - libtorch=2.7.1=cuda129_mkl_h16584c3_301
  - libudev1=257.7=hbe16f8c_0
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.7=h024ca30_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py311h8c6ae76_0
  - lz4-c=1.10.0=h5888daf_1
  - magma=2.9.0=h622db9b_1
  - markdown=3.8.2=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib=3.10.3=py311h38be061_0
  - matplotlib-base=3.10.3=py311h2b939e6_0
  - mkl=2024.2.2=ha957f24_16
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - mpi4py=4.0.3=py311hea7032f_101
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py311hd18a35c_0
  - multiurl=0.3.7=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.0.1=pyhe01879c_0
  - nccl=2.27.5.1=h9b8ff78_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numpy=1.26.4=py311h64a7726_0
  - openfst=1.8.3=h84d6215_3
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openmpi=5.0.7=external_ha35b396_2
  - openssl=3.5.4=h26f9b46_0
  - optree=0.16.0=py311hd18a35c_0
  - orc=2.1.2=h17f744e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py311h7db5c69_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=hc749103_0
  - pillow=11.3.0=py311h1322bbf_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h29eaf8c_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - protobuf=5.29.3=py311h3a6f5f3_0
  - psutil=7.0.0=py311h9ecbd09_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=20.0.0=py311h38be061_0
  - pyarrow-core=20.0.0=py311hcae7c52_0_cuda
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.1=py311h846acb3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.13=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.11.13=hd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytorch=2.7.1=cuda129_mkl_py311_hb55e5d5_301
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.1=h0384650_1
  - rav1e=0.7.1=h8fae777_3
  - rdma-core=57.0=h5888daf_0
  - re2=2025.06.26=h9925aae_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - rhash=1.4.6=hb9d3cd8_1
  - s2n=1.5.22=h96f233e_0
  - safetensors=0.6.2=py311hc8fb587_0
  - scikit-learn=1.7.1=py311hc3e1efb_0
  - scipy=1.16.1=py311h33d6a90_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=59.8.0=py311h38be061_1
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - snappy=1.2.2=h03e3b7b_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311hb0beb2c_0
  - svt-av1=3.1.1=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hceb3a55_1
  - tblib=3.1.0=pyhd8ed1ab_0
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py311hafd3f86_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - timm=1.0.19=pyhe01879c_0
  - tk=8.6.13=noxft_hd72426e_102
  - toolz=1.0.0=pyhd8ed1ab_1
  - torchaudio=2.7.1=cuda126_py311h7a4b964_1
  - torchvision=0.22.0=cuda_py311_h2942a37_2
  - torchvision-extra-decoders=0.0.2=py311ha44aed6_3
  - tornado=6.5.1=py311h9ecbd09_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - triton=3.3.1=cuda126py311h126903f_1
  - typing-extensions=4.14.0=h32cad80_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ucc=1.4.4=ha3c1411_0
  - ucx=1.18.1=hb51fc76_0
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x265=3.5=h924138e_3
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py311h9ecbd09_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - cftime==1.6.4.post1
      - netcdf4==1.7.1.post1
      - torchsummary==1.5.1
prefix: /home/ouc/zhuxianrui/environment/miniconda3/envs/pycm2
